src/FullFraim/FullFraim.Web/Controllers/ApiControllers/DashboardController.cs
using FullFraim.Models.Dto_s.Contests;
using FullFraim.Models.Dto_s.Pagination;
using FullFraim.Services.ContestServices;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FullFraim.Web.Controllers.ApiControllers
{
    [ApiController]
    [Route("api/[Controller]")]
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public class DashboardController : ControllerBase
    {
        private readonly IContestService contestService;

        public DashboardController(IContestService contestService)
        {
            this.contestService = contestService;
        }

        /// <summary>
        /// used to get contest without additional information
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="categoryId"></param>
        /// <param name="paginationFilter"></param>
        /// <returns></returns>
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ICollection<OutputContestDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status401Unauthorized)]
        public async Task<IActionResult> GetAll([FromQuery] int userId, string phase, int categoryId, [FromQuery] PaginationFilter paginationFilter)
        {
            if (userId <= 0)
            {
                return BadRequest();
            }

            var allForUser = await this.contestService.GetAllForUserByPhaseAsync(userId, paginationFilter, categoryId, phase);

            return Ok(allForUser);
        }
    }
}

src/FullFraim/FullFraim.Web/Controllers/DashboardController.cs
using FullFraim.Models.Dto_s.Pagination;
using FullFraim.Models.Dto_s.Reviews;
using FullFraim.Models.ViewModels.Contest;
using FullFraim.Models.ViewModels.Dashboard;
using FullFraim.Models.ViewModels.Enrolling;
using FullFraim.Services.ContestCatgeoryServices;
using FullFraim.Services.ContestServices;
using FullFraim.Services.JuryServices;
using FullFraim.Services.PhotoJunkieServices;
using FullFraim.Services.PhotoService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shared;
using Shared.AllConstants;
using System.Linq;
using System.Threading.Tasks;
using Utilities.CloudinaryUtils;
using Utilities.Mapper;

namespace FullFraim.Web.Controllers
{
    [Authorize]
    public class DashboardController : BaseMvcController
    {
        private readonly IContestService contestService;
        private readonly IContestCategoryService contestCategoryService;
        private readonly IPhotoJunkieService photoJunkieService;
        private readonly IJuryService juryService;
        private readonly IPhotoService photoService;
        private readonly ICloudinaryUtils cloudinaryService;

        public DashboardController(IContestService contestService,
            IContestCategoryService contestCategoryService,
            IPhotoJunkieService photoJunkieService,
            IJuryService juryService,
            IPhotoService photoService,
            ICloudinaryUtils cloudinaryService)
        {
            this.contestService = contestService;
            this.contestCategoryService = contestCategoryService;
            this.photoJunkieService = photoJunkieService;
            this.juryService = juryService;
            this.photoService = photoService;
            this.cloudinaryService = cloudinaryService;
        }

        public async Task<IActionResult> Index(int categoryId, PaginationFilter paginationFilter)
        {
            // Default page size for this page
            paginationFilter.PageSize = 4;

            var dashboardPaginatedViewModel = new DashboardPhasesPaginatedViewModel()
            {
                PhaseOne = await GetContestViewModelByPhaseAsync(categoryId, paginationFilter, Constants.Phases.PhaseI),
                PhaseTwo = await GetContestViewModelByPhaseAsync(categoryId, paginationFilter, Constants.Phases.PhaseII),
                Finished = await GetContestViewModelByPhaseAsync(categoryId, paginationFilter, Constants.Phases.Finished),
            };

            dashboardPaginatedViewModel.PhaseOne.CurrentPage = paginationFilter.PageNumber;
            dashboardPaginatedViewModel.PhaseTwo.CurrentPage = paginationFilter.PageNumber;
            dashboardPaginatedViewModel.Finished.CurrentPage = paginationFilter.PageNumber;

            ViewBag.Categories = await this.contestCategoryService.GetAllAsync();

            return View(dashboardPaginatedViewModel);
        }

        public async Task<IActionResult> ContestPhaseNavigation(int categoryId, PaginationFilter paginationFilter, string phase)
        {
            paginationFilter.PageSize = 4;

            var contests = await this.GetContestViewModelByPhaseAsync(categoryId, paginationFilter, phase);
            contests.CurrentPage = paginationFilter.PageNumber;

            return PartialView("~/Views/Shared/Partials/_ContestCardPartial.cshtml", contests);
        }

        public IActionResult Enroll(int contestId)
        {
            return PartialView("~/Views/Shared/Partials/_EnrollPartial.cshtml",
                new EnrollViewModel() { ContestId = contestId });
        }

        [HttpPost]
        public async Task<IActionResult> Enroll(EnrollViewModel model)
        {
            model.UserId = UserId;

            // Cannot enroll if user is jury for contest
            if (await this.photoJunkieService.IsUserJury(model.ContestId, this.UserId))
            {
                ModelState
                    .AddModelError(string.Empty,
                    errorMessage: ErrorMessages.CannotEnroll);
            }

            if (!ModelState.IsValid)
            {
                return PartialView("~/Views/Shared/Partials/_EnrollPartial.cshtml", model);
            }

            string imageUrl = this.cloudinaryService
                .UploadImage(model.Photo);

            await photoJunkieService
                .EnrollForContestAsync(model.MapToDto(imageUrl));

            return Json(new { isValid = true });
        }

        public async Task<IActionResult> GetById(int id, PaginationFilter paginationFilter)
        {
            int userId = UserId;
            var contestSubmissions = await this.photoService
                .GetDetailedSubmissionsFromContestAsync(id, paginationFilter);

            foreach (var item in contestSubmissions.Model)
            {
                item.HasJuryGivenReview = await this.juryService.HasJuryAlreadyGivenReviewAsync(UserId, item.PhotoId);
            }

            var paginatedModel = new PaginatedModel<ContestSubmissionViewModel>()
            {
                Model = contestSubmissions.Model.Select(m => m.MapToContestSubmissionView())
                     .ToList(),
                RecordsPerPage = contestSubmissions.RecordsPerPage,
                TotalPages = contestSubmissions.TotalPages,
            };
            var contest = await this.contestService.GetByIdAsync(id);

            ViewData["Title"] = contest.Name;
            ViewData["Category"] = contest.ContestCategory;

            return View(paginatedModel);
        }

        public async Task<IActionResult> GetByIdUserSubmission(int id)
        {
            int userId = UserId;

            var submission = (await this.photoService
                .GetUserSubmissionForContestAsync(userId, id)
                ).MapToUserSubmissionViewModel();

            var contest = await this.contestService.GetByIdAsync(id);

            submission.ContestName = contest.Name;
            submission.ContestCatrogry = contest.ContestCategory;

            return View(submission);
        }

        public async Task<IActionResult> GiveReview(int contestId, int submitterId)
        {
            // Checks if user is jury and if phase is phase two
            if (!((await this.contestService.GetByIdAsync(contestId)).ActivePhase.Name == Constants.Phases.PhaseII &&
                await this.juryService.IsUserJuryForContest(contestId, UserId)))
            {
                return Unauthorized();
            }

            var submission = await this.photoService.GetUserSubmissionForContestAsync(submitterId, contestId);

            var giveReviewViewModel = new GiveReviewViewModel
            {
                PhotoUrl = submission.Url,
                Author = submission.SubmitterName,
                Description = submission.Description,
                Title = submission.Title,
                HasJuryGivenReview = await this.juryService.IsJuryGivenReviewForPhotoAsync(submission.Id, this.UserId)
            };

            if (giveReviewViewModel.HasJuryGivenReview)
            {
                var review = await this.juryService.GetReviewAsync(UserId, submission.Id);
                giveReviewViewModel.Review = new InputGiveReviewDto()
                {
                    Score = review.Score,
                    Comment = review.Comment,
                    Checkbox = review.IsDisqualified,
                };
            }
            else
            {
                giveReviewViewModel.Review = new InputGiveReviewDto()
                {
                    JuryId = this.UserId,
                    PhotoId = submission.Id,
                };
            }

            return View("~/Views/Dashboard/GiveReview.cshtml",
                giveReviewViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> GiveReview(GiveReviewViewModel model)
        {
            model.JuryId = UserId;

            if (!await juryService.IsContestInPhaseTwoAsync(model.Review.PhotoId))
            {
                ModelState
                   .AddModelError(string.Empty,
                   errorMessage: ErrorMessages.ReviewOutsidePhaseTwo);
            }

            if (!ModelState.IsValid)
            {
                return View("~/Views/Dashboard/GiveReview.cshtml", model);
            }

            if (await juryService.HasJuryAlreadyGivenReviewAsync(model.JuryId, model.PhotoId))
            {
                ModelState
                   .AddModelError(string.Empty,
                   errorMessage: ErrorMessages.ReviewAlreadyGiven);
            }

            var review = await this.juryService.GiveReviewAsync(model.MapToInputGiveReviewDto());
            model.HasJuryGivenReview = true;

            TempData["success"] = Constants.SuccessMessages.GivenReviewSuccess;

            return RedirectToAction(nameof(GetById), new { id = review.ContestId });
        }

        public async Task<IActionResult> DetailsReview(int contestId, int photoId, PaginationFilter paginationFilter)
        {
            //Checks if user is participant/jury and if contest is in phase - Finished
            if (!((await this.juryService.IsUserJuryForContest(contestId, UserId) ||
                await this.photoJunkieService.IsUserParticipant(contestId, this.UserId)) &&
                await this.contestService.IsContestInPhaseFinished(contestId)))
            {
                return Unauthorized();
            }

            var submissions = await this.photoService.GetDetailedSubmissionsForPhoto(contestId, photoId, paginationFilter);

            return View(submissions);
        }

        private async Task<PaginatedModel<DashboardViewModel>> GetContestViewModelByPhaseAsync(int categoryId, PaginationFilter paginationFilter, string phase)
        {
            var phaseOneContests = await this.contestService.GetAllForUserByPhaseAsync(UserId, paginationFilter, categoryId, phase);

            var contestByPhaseViewModel = new PaginatedModel<DashboardViewModel>()
            {

src/FullFraim/FullFraim.Web/ViewComponents/PointsTillNextViewComponent.cs
using FullFraim.Data;
using FullFraim.Data.Models;
using FullFraim.Models.ViewModels.Dashboard;
using FullFraim.Services.PhotoJunkieServices;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Utilities.Mapper;

namespace FullFraim.Web.ViewComponents
{
    public class PointsTillNextViewComponent : ViewComponent
    {
        private readonly IPhotoJunkieService photoJunkieService;
        private readonly UserManager<User> userManager;
        private readonly IConfiguration configuration;
        private readonly FullFraimDbContext context;

        public PointsTillNextViewComponent
            (IPhotoJunkieService photoJunkieService,
            UserManager<User> userManager,
            IConfiguration configuration,
            FullFraimDbContext context)
        {
            this.photoJunkieService = photoJunkieService;
            this.userManager = userManager;
            this.configuration = configuration;
            this.context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var junkies = await userManager.Users
                .Where(x => x.FirstName != configuration["AccountAdminInfo:UserName"])
                .OrderByDescending(r => r.Points)
                .Take(5)
                .ToListAsync();

            var result = new List<RankAndPointsViewModel>();

            foreach (var junkie in junkies)
            {
                var photojunkieWithPoints = await photoJunkieService
                    .GetPointsTillNextRankAsync(junkie.Id);

                result
                    .Add(photojunkieWithPoints
                    .MapToPointsViewModel
                    ($"{junkie.FirstName} {junkie.LastName}"));
            }

            result = result.ToList();

            ViewBag.CurrentUser = await GetCurrentUserPointsAsync();

            return View(result);
        }

        private async Task<CurrentUserViewModel> GetCurrentUserPointsAsync()
        {
            var id = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);

            var user = await this.context.Users
                .Where(x => x.Id == id)
                .Select(x => new { x.FirstName, x.LastName, x.Points })
                .FirstOrDefaultAsync();

            var pointsTillNext = await photoJunkieService
                    .GetPointsTillNextRankAsync(id);

            var result = new CurrentUserViewModel()
            {
                CurrentPoints = (int)user.Points,
                Ranking = pointsTillNext.MapToPointsViewModel($"{user.FirstName} {user.LastName}"),
                Rank = pointsTillNext.Rank,
            };

            return result;
        }
    }
}

src/FullFraim/FullFraim.Web/Views/Dashboard/DetailsReview.cshtml
@model PaginatedModel<ContestSubmissionOutputDto>
@{
    var score = $"{Model.Model.FirstOrDefault().Score:f2}";
}
<link rel="stylesheet" href="~/css/Identity/Login.css" />
<link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />

<div style="margin: 15vh 0rem 0rem 0rem">
    <div class="wrapper fadeInDown">
        <div id="formContent" style="max-width: 60rem !important">
            <div style="margin-top:3rem;">
                <img class="card-img-top" src="@Model.Model.FirstOrDefault().PhotoUrl" alt="Card image cap" style="width: 95%; border-radius: 15px;" />
                <p>Author: <i>@Model.Model.FirstOrDefault().AuthorName</i></p>
                <p><q><i>@Model.Model.FirstOrDefault().Description</i></q></p>
            </div>
            <div class="fadeIn first" style="margin-top: 1rem;">
                <h6>
                    Final score: <span style="color: gray">
                        <svg xmlns="http://www.w3.org/2000/svg" width="12" height="16" fill="currentColor" class="bi bi-star-half" viewBox="0 0 16 16">
                            <path d="M5.354 5.119 7.538.792A.516.516 0 0 1 8 .5c.183 0 .366.097.465.292l2.184 4.327 4.898.696A.537.537 0 0 1 16 6.32a.548.548 0 0 1-.17.445l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256a.52.52 0 0 1-.146.05c-.342.06-.668-.254-.6-.642l.83-4.73L.173 6.765a.55.55 0 0 1-.172-.403.58.58 0 0 1 .085-.302.513.513 0 0 1 .37-.245l4.898-.696zM8 12.027a.5.5 0 0 1 .232.056l3.686 1.894-.694-3.957a.565.565 0 0 1 .162-.505l2.907-2.77-4.052-.576a.525.525 0 0 1-.393-.288L8.001 2.223 8 2.226v9.8z" />
                        </svg>
                        @score / 10
                    </span>
                </h6>
            </div>
            <hr />
            <div style="overflow-y:scroll; max-height: 27rem;">
                @foreach (var review in Model.Model)
                {
                    @foreach (var Review in review.Reviews)
                    {
                        <div>
                            <p>Review by: <i>@Review.AuthorName</i></p>
                            <div class="form-group">
                                <label asp-for="@Review.Comment"></label>
                                <div>
                                    <p class="fadeIn second"><q>@Review.Comment</q></p>
                                </div>
                            </div>

                            <div class="form-group">

                                <div class="slidecontainer">
                                    <h7>
                                        Score: <span style="color:gray;">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="16" fill="currentColor" class="bi bi-star-half" viewBox="0 0 16 16">
                                                <path d="M5.354 5.119 7.538.792A.516.516 0 0 1 8 .5c.183 0 .366.097.465.292l2.184 4.327 4.898.696A.537.537 0 0 1 16 6.32a.548.548 0 0 1-.17.445l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256a.52.52 0 0 1-.146.05c-.342.06-.668-.254-.6-.642l.83-4.73L.173 6.765a.55.55 0 0 1-.172-.403.58.58 0 0 1 .085-.302.513.513 0 0 1 .37-.245l4.898-.696zM8 12.027a.5.5 0 0 1 .232.056l3.686 1.894-.694-3.957a.565.565 0 0 1 .162-.505l2.907-2.77-4.052-.576a.525.525 0 0 1-.393-.288L8.001 2.223 8 2.226v9.8z" />
                                            </svg>
                                            @Review.Score
                                        </span>
                                    </h7>
                                </div>
                            </div>
                        </div>
                        <hr />
                    }
                }
            </div>
        </div>
    </div>
</div>

src/FullFraim/FullFraim.Web/Views/Dashboard/GetByIdUserSubmission.cshtml
@model UserSubmissionViewModel

<div class="gallery_area clearfix">
    <h5 style="text-align:center; color:gray;">@Model.ContestName</h5>
    <h5 style="text-align:center; color: cornflowerblue;">@Model.ContestCatrogry</h5>
    <div class="container-fluid clearfix">
        <div class="row portfolio-column">

            <partial name="~/Views/Shared/Partials/_ContestUserSubmissionPartial.cshtml" model="Model" />

        </div>
    </div>
</div>

src/FullFraim/FullFraim.Web/Views/Dashboard/GiveReview.cshtml
@model GiveReviewViewModel

<link rel="stylesheet" href="~/css/Identity/Login.css" />
<link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />

@if (Model.HasJuryGivenReview)
{
    <div style="margin: 15vh 0rem 0rem 0rem">
        <div class="wrapper fadeInDown">
            <div id="formContent" style="max-width: 60rem !important">
                <div style="margin-top:3rem;">
                    <p>@Model.Author</p>
                    <img class="card-img-top" src="@Model.PhotoUrl" alt="Card image cap" style="width: 75%; height:50%" />
                    <p>@Model.Description</p>
                </div>
                    <input asp-for="Review.PhotoId" hidden />
                    <input asp-for="Review.JuryId" hidden />
                    <div class="fadeIn first" style="margin-top: 1rem;">
                        <h5 style="display: inline-block">Give Review</h5>
                    </div>
                    <hr />

                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Review.Comment"></label>
                        <textarea asp-for="Review.Comment" class="form-control fadeIn second" readonly ></textarea>
                        <span asp-validation-for="Review.Comment" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <h5>Score</h5>
                        <p>Drag the slider to display the current value.</p>
                        <div class="slidecontainer">
                            <input asp-for="Review.Score" type="range" min="0" max="10" value="@Model.Review.Score" class="slider" style="width: 100%" id="myRange" disabled>
                            <p>Score: <span id="demo"></span></p>
                        </div>
                    </div>

                    <div class="custom-control custom-switch">
                        <input asp-for="Review.Checkbox" class="custom-control-input" disabled id="customSwitch2">
                        <label class="custom-control-label" for="customSwitch2">Photo does not fit contest category</label>
                    </div>

                    <div class="form-group formFooter">
                        <div class="form-group">
                            <button formmethod="post" class="btn btn-secondary fadeIn fourth" disabled>Already submited</button>
                        </div>
                    </div>
            </div>
        </div>
    </div>
}
else
{
    <div style="margin: 15vh 0rem 0rem 0rem">
        <div class="wrapper fadeInDown">
            <div id="formContent" style="max-width: 60rem !important">
                <div style="margin-top:3rem;">
                    <p>@Model.Author</p>
                    <img class="card-img-top" src="@Model.PhotoUrl" alt="Card image cap" style="width: 75%; height:50%" />
                    <p>@Model.Description</p>
                </div>
                <form id="account" asp-controller="Dashboard" asp-action="GiveReview" method="post">
                    <input asp-for="Review.PhotoId" hidden />
                    <input asp-for="Review.JuryId" hidden />
                    <input asp-for="PhotoId" hidden />
                    <input asp-for="Review.PhotoId" hidden />
                    <input asp-for="PhotoUrl" hidden />
                    <div class="fadeIn first" style="margin-top: 1rem;">
                        <h5 style="display: inline-block">Give Review</h5>
                    </div>
                    <hr />
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Review.Comment"></label>
                        <textarea asp-for="Review.Comment" class="form-control fadeIn second" placeholder="Comment.." ></textarea>
                        <span asp-validation-for="Review.Comment" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <h5>Score</h5>
                        <p>Drag the slider to display the current value.</p>
                        <div class="slidecontainer">
                            <input asp-for="Review.Score" type="range" min="1" max="10" value="1" class="slider" style="width: 100%" id="myRange">
                            <p>Score: <span id="demo"></span></p>
                        </div>
                    </div>

                    <div class="custom-control custom-switch">
                        <input asp-for="Review.Checkbox" class="custom-control-input" id="customSwitch1">
                        <label class="custom-control-label" for="customSwitch1">Photo does not fit contest category</label>
                    </div>

                    <div class="form-group formFooter">
                        <div class="form-group">
                            <p>Please note: You can give one review for this photo, once you submit it you won't be able to make changes</p>
                            <button type="submit"  formmethod="post" class="btn btn-primary fadeIn fourth">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
}




@section Scripts{
    <script>
        var slider = document.getElementById("myRange");
        var output = document.getElementById("demo");
        output.innerHTML = slider.value;



        slider.oninput = function () {
            output.innerHTML = this.value;
        }</script>
}

src/FullFraim/FullFraim.Web/Views/Dashboard/Index.cshtml
@model DashboardPhasesPaginatedViewModel

<style>
    .paging {
        display: flex;
        flex-wrap: nowrap;
        flex-direction: row;
        align-content: center;
        justify-content: center;
        width: 100%;
        margin-top: 1rem;
    }
</style>

<div class="top-users" style="height: 87%">
    @await Component.InvokeAsync("PointsTillNext")
</div>
<div class="gallery_area clearfix" style="border-left: solid 1px lightgray">
    <div class="container-fluid clearfix">
        @if (TempData["success"] != null)
        {
            <div class="alert alert-success">
                <strong>Success!</strong> @TempData["success"]
            </div>
        }
        <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
            <ul class="dropdown-menu">
                <li>
                    <a class="dropdown-item" asp-controller="Dashboard" asp-action="Index"
                       asp-route-categoryId="0">All</a>
                    @foreach (var category in ViewBag.Categories)
                    {
                        <a class="dropdown-item" test="categoryId" asp-controller="Dashboard" asp-action="Index"
                           asp-route-categoryId="@category.Id">@category.Name</a>
                    }
                </li>
            </ul>
        </div>
        <div style="margin-bottom: 1rem;margin-top: 1rem;">Open</div>
        <div tabindex="1" id="focus-element" hidden>
        </div>
        <div>
            <div class="row portfolio-column" id="ajax-pagination-phaseOne">
                <partial name="~/Views/Shared/Partials/_ContestCardPartial.cshtml" model="Model.PhaseOne" />

            </div>
        </div>
        <div style="margin-bottom: 1rem;margin-top: 4rem;">Reviewing</div>
        <div class="row portfolio-column">
            <div class="row portfolio-column" id="ajax-pagination-phaseTwo">
                <partial name="~/Views/Shared/Partials/_ContestCardPartial.cshtml" model="Model.PhaseTwo" />

            </div>
        </div>
        <div style="margin-bottom:1rem;margin-top: 4rem;">Closed</div>
        <div class="row portfolio-column">
            <div class="row portfolio-column" id="ajax-pagination-finished">
                <partial name="~/Views/Shared/Partials/_ContestCardPartial.cshtml" model="Model.Finished" />

            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        function paginationPhase(event, url) {
            event.preventDefault();
            event.stopPropagation();

            var categoryQuery = '';

            var queries = location.href.split('?')[1]
            if (queries != undefined) {
                queries = queries.split('&');

                for (var i = 0; i < queries.length; i++) {
                    var query = queries[i].split('=');
                    if (query[0] == 'categoryId') {
                        categoryQuery = '&' + query[0] + '=' + query[1];
                        break;
                    }
                }
            }

            if (event.currentTarget.classList.contains('PhaseI')) {
                var phaseOneUrl = url + '&phase=PhaseI'
                $.ajax({
                    url: phaseOneUrl + categoryQuery,
                    success: function (res) {
                        $('#ajax-pagination-phaseOne').html('');
                        $('#ajax-pagination-phaseOne').html(res);
                    }
                });

                $('#ajax-pagination-phaseOne').focus();

            }
            if (event.currentTarget.classList.contains('PhaseII')) {

                $.ajax({
                    url: url + '&phase=PhaseII' + categoryQuery,
                    success: function (res) {
                        $('#ajax-pagination-phaseTwo').html('');
                        $('#ajax-pagination-phaseTwo').html(res);
                    }
                });

                $('#ajax-pagination-phaseTwo').focus();
            }
            if (event.currentTarget.classList.contains('finished')) {

                $.ajax({
                    url: url + '&phase=finished' + categoryQuery,
                    success: function (res) {
                        $('#ajax-pagination-finished').html('');
                        $('#ajax-pagination-finished').html(res);
                    }
                });

                $('#ajax-pagination-finished').focus();
            }
            return false;
        }

    </script>

    <script>
        $(document).ready(function () {
            OpenModal = (url, title, id) => {
                $.ajax({
                    type: "GET",
                    url: url,
                    data: { contestId: id },
                    success: function (response) {
                        $(".modal-title").html(title);
                        $(".modal-body").html(response);
                    }
                });
            }
        });
    </script>
}