src/FullFraim/FullFraim.Web/Controllers/ContestController.cs
using FullFraim.Models.Contest.ViewModels;
using FullFraim.Models.Dto_s.Pagination;
using FullFraim.Services.ContestCatgeoryServices;
using FullFraim.Services.ContestServices;
using FullFraim.Services.ContestTypeServices;
using FullFraim.Services.PhaseServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shared;
using Shared.AllConstants;
using System;
using System.Linq;
using System.Threading.Tasks;
using Utilities.CloudinaryUtils;
using Utilities.Mapper;

namespace FullFraim.Web.Controllers
{
    [Authorize]
    [Controller]
    public class ContestController : BaseMvcController
    {
        private readonly IContestService contestService;
        private readonly IContestCategoryService contestCategoryService;
        private readonly IPhaseService phaseService;
        private readonly IContestTypeService contestTypeService;
        private readonly ICloudinaryUtils cloudinaryService;

        public ContestController(IContestService contestService,
            IContestCategoryService contestCategoryService,
            IPhaseService phaseService,
            IContestTypeService contestTypeService,
            ICloudinaryUtils cloudinaryService)
        {
            this.contestService = contestService;
            this.contestCategoryService = contestCategoryService;
            this.phaseService = phaseService;
            this.contestTypeService = contestTypeService;
            this.cloudinaryService = cloudinaryService;
        }

        public async Task<IActionResult> Create()
        {
            await SeedDropdownsForContest();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateContestViewModel model)
        {
            foreach (var jury in model.Juries)
            {
                if (model.Participants.Contains(jury))
                {
                    ModelState.AddModelError(string.Empty, ErrorMessages.JuryCannotBeParticipant);
                    break;
                }
            }

            if (!await this.contestService.IsNameUniqueAsync(model.Name))
            {
                ModelState.AddModelError(string.Empty, ErrorMessages.NameMustBeUnique);
            }

            if (model.Cover_Url != null && model.Cover != null)
            {
                ModelState
                    .AddModelError(string.Empty, ErrorMessages.CannotSendBothUrlAndImage);
            }

            if (model.Cover == null && model.Cover_Url == null)
            {
                ModelState
                    .AddModelError(string.Empty, ErrorMessages.ContestCoverRequired);
            }

            if (!ModelState.IsValid)
            {
                await SeedDropdownsForContest();

                return View(model);
            }

            var invitationalContestTypeId =
                (await this.contestTypeService.GetAllAsync())
                    .FirstOrDefault(ct => ct.Name == Constants.ContestType.Invitational).Id;

            if (model.ContestTypeId == invitationalContestTypeId &&
                    model.Juries == null &&
                    model.Participants == null)
            {
                throw new Exception();
            }

            if (model.Cover != null && model.Cover_Url == null)
            {
                model.Cover_Url = this.cloudinaryService.UploadImage(model.Cover);
            }

            var contest = await this.contestService.CreateAsync(model.MapToDto());

            TempData["success"] = Constants.SuccessMessages.CreateContestSuccess;

            return RedirectToAction(nameof(DashboardController.Index),
                nameof(DashboardController).Replace("Controller", string.Empty));
        }

        [HttpGet]
        public async Task<IActionResult> ChooseCovers()
        {
            var result = await this.contestService.GetContestCoversAsync(new PaginationFilter());

            ViewBag.Covers = result;

            return View();
        }

        [NonAction]
        private async Task SeedDropdownsForContest()
        {
            ViewBag.Categories = await this.contestCategoryService
                    .GetAllAsync();

            ViewBag.Phases = await this.phaseService
                .GetAllAsync();

            ViewBag.ContestTypes = await this.contestTypeService
                .GetAllAsync();

            ViewBag.Jury = (await this.contestService.GetPotentialJuryForInvitationAsync()).MapToDropDownView();
            ViewBag.Participants = (await this.contestService.GetParticipantsForInvitationAsync()).MapToDropDownView();
        }
    }
}

src/FullFraim/FullFraim.Web/Controllers/UserController.cs
using FullFraim.Data.Models;
using FullFraim.Models.Dto_s.Pagination;
using FullFraim.Models.ViewModels.Dashboard;
using FullFraim.Models.ViewModels.Sorting;
using FullFraim.Models.ViewModels.User;
using FullFraim.Services.PhotoJunkieServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using System.Threading.Tasks;
using Utilities.Mapper;
using static Shared.Constants;

namespace FullFraim.Web.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly IPhotoJunkieService photoJunkieService;
        private readonly UserManager<User> userManager;
        private static readonly List<SortingViewModel> sortingCollection = new List<SortingViewModel>()
        {
            new SortingViewModel()
            {
                ViewName = Sorting.FirstNameAscView,
                ServerName = Sorting.FirstNameAsc
            },
            new SortingViewModel()
            {
                ViewName = Sorting.FirstNameDescView,
                ServerName = Sorting.FirstNameDesc
            },
            new SortingViewModel()
            {
                ViewName = Sorting.LastNameAscView,
                ServerName = Sorting.LastNameAsc
            },
            new SortingViewModel()
            {
                ViewName = Sorting.LastNameDescView,
                ServerName = Sorting.LastNameDesc
            },
            new SortingViewModel()
            {
                ViewName = Sorting.RankAscView,
                ServerName = Sorting.RankAsc
            },
            new SortingViewModel()
            {
                ViewName = Sorting.RankDescView,
                ServerName = Sorting.RankDesc
            },
            new SortingViewModel()
            {
                ViewName = Sorting.PointsAscView,
                ServerName = Sorting.PointsAsc
            },
            new SortingViewModel()
            {
                ViewName = Sorting.PointsDescView,
                ServerName = Sorting.PointsDesc
            }
        };

        public UserController(IConfiguration configuration,
            IPhotoJunkieService photoJunkieService,
            UserManager<User> userManager)
        {
            this.configuration = configuration;
            this.photoJunkieService = photoJunkieService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index([FromQuery] string orderBy = "", [FromQuery] int pageNumber = 1)
        {
            var paginationFilter = new PaginationFilter() { PageNumber = pageNumber };

            var junkies = await this.photoJunkieService
                .GetAllAsync(new SortingModel() { OrderBy = orderBy },
                paginationFilter);

            var result = new List<RankAndPointsViewModel>();

            foreach (var junkie in junkies.Model)
            {
                var photojunkieWithPoints = await photoJunkieService
                    .GetPointsTillNextRankAsync(junkie.Id);

                result
                    .Add(photojunkieWithPoints
                    .MapToPointsViewModel
                    (junkie.FirstName + junkie.LastName));
            }

            ViewBag.Sorting = sortingCollection;

            var ViewResult = new UsersPageViewModel()
            {
                Sorting = orderBy,
                Model = result,
                PaginatedModel = junkies,
                PageFilter = paginationFilter,
            };

            return View(ViewResult);
        }
    }
}

src/FullFraim/FullFraim.Web/Views/Shared/Partials/_CarouselPartial.cshtml
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://coosemanstore.com/wp-content/uploads/2018/08/recipe8-680x380.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Spaghetti code winner 1st place</h5>
                <p>Boryana Mihaylova.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://coosemanstore.com/wp-content/uploads/2018/08/recipe8-680x380.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Spaghetti code winner 2nd place</h5>
                <p>Valentin Shikov.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://www.curiosaportugal.com/wp-content/uploads/2021/01/Spaghetti-with-stuffed-meatball-in-tomato-sauce-recipe-680x380.png" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Spaghetti code winner 3rd place</h5>
                <p>Ivan Dichev.</p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

src/FullFraim/FullFraim.Web/Views/Shared/Partials/_ContactFormPartial.cshtml
@using FullFraim.Models.ViewModels.ContactUs
@model ContactUsInputModel

<div class="contact-form-area">
    <div class="container-fluid">
        <form asp-action="ContactUs" asp-controller="Home" method="post">
            <div class="row">
                <div class="col-12 col-md-4">
                    <input asp-for="Name" type="text" class="form-control" name="name" id="name" placeholder="Your Name">
                </div>
                <div class="col-12 col-md-4">
                    <input asp-for="Email" type="email" class="form-control" name="email" id="email" placeholder="Your Email">
                </div>
                <div class="col-12 col-md-4">
                    <input asp-for="Subject" type="text" class="form-control" name="subject" id="subject" placeholder="Subject">
                </div>
                <div class="col-12">
                    <textarea asp-for="Message" name="message" class="form-control" id="message" cols="30" rows="10" placeholder="Message"></textarea>
                </div>
                <div class="col-12 text-center">
                    <button type="submit" class="btn studio-btn mt-3">
                        <img src="~/img/core-img/logo-icon.png" alt=""> Send
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

src/FullFraim/FullFraim.Web/Views/Shared/Partials/_ContestCardPartial.cshtml
@model PaginatedModel<DashboardViewModel>
@{
    var paginationModel = new PaginationPartialModel()
    {
        TotalPages = Model.TotalPages,
        Action = "ContestPhaseNavigation",
        Controller = "Dashboard",
        PageNumber = Model.CurrentPage,
    };

    if (Model.Model.Count != 0)
    {
        paginationModel.Phase = Model?.Model?.FirstOrDefault().ActivePhase.Name;
    }
}

<script src="~/lib/jquery/jquery.js"></script>

<div class="row portfolio-column" style="margin-left:1.5rem;">
    @foreach (var contest in Model.Model)
    {
        <div class="card" style="margin-inline:1rem; margin-bottom:1rem;">

            <img class="card-img-top" src="@contest.Cover_Url" alt="Card image cap" style="width: 300px; height:200px">
            <div class="card-body" style="text-align: center;display: flex;flex-direction: column;justify-content: space-between;align-items: center;flex-wrap: wrap; max-width: 300px;">
                <div>
                    <h5 class="card-title">@contest.Name</h5>
                    <p class="card-text">@contest.Description</p>
                    <p class="card-text">@contest.CategoryName</p>
                    @if (contest.ActivePhase.Name != "Finished")
                    {
                        <div>
                            Deadline in <p style="color: blue" id="demo">
                                @contest.ActivePhase.EndDate.ToString("MM.dd HH:mm")
                            </p>
                        </div>
                    }
                </div>
                @if (contest.ActivePhase.Name == "PhaseI")
                {
                    @if (contest.IsCurrentUserParticipant && contest.HasCurrentUserSybmittedPhoto)
                    {
                        <div>
                            <a asp-action="GetByIdUserSubmission" asp-controller="Dashboard" asp-route-id="@contest.ContestId"
                               class="btn-outline-primary btn-sm contestDetail">Review</a>
                        </div>
                    }
                    else if (contest.IsCurrentUserJury)
                    {
                        <div>
                            <a asp-action="GetById" asp-controller="Dashboard" asp-route-id="@contest.ContestId"
                               class="btn-outline-primary btn-sm contestDetail">Review</a>
                        </div>
                    }
                    else
                    {
                        <a data-toggle="modal" data-target=".contact-modal-lg" class="btn-sm btn-outline-primary hover-white" style="cursor: pointer;color:#408dff"
                           onclick="OpenModal('@Url.Action("Enroll", "Dashboard", null, Context.Request.Scheme)', 'Enroll', @contest.ContestId)">Enroll</a>
                    }
                }
                else if (contest.ActivePhase.Name == "PhaseII")
                {
                    <p>Closed for enrollement</p>

                    @if (contest.IsCurrentUserParticipant)
                    {
                        <a asp-action="GetByIdUserSubmission" asp-controller="Dashboard" asp-route-id="@contest.ContestId"
                           class="btn-outline-primary btn-sm contestDetail">Review</a>
                    }
                    else if (contest.IsCurrentUserJury)@*If jury*@
                    {
                        @if (contest.IsCurrentUserParticipant || contest.IsCurrentUserJury)
                        {
                            <a asp-action="GetById" asp-controller="Dashboard" asp-route-id="@contest.ContestId"
                               class="btn-outline-primary btn-sm contestDetail">Review</a>
                        }
                    }
                }
                else if (contest.ActivePhase.Name == "Finished")
                {
                    <p>Finished</p>

                    @if (contest.IsCurrentUserParticipant || contest.IsCurrentUserJury)
                    {
                        <a asp-action="GetById" asp-controller="Dashboard" asp-route-id="@contest.ContestId"
                           class="btn-outline-primary btn-sm contestDetail">Review</a>
                    }
                }

            </div>
        </div>
    }
    @if (Model.Model.Count == 0)
    {
        <div style="margin-left:10rem;">
            <h5>Nothing to see here.</h5>
            <hr />
            <img src="https://res.cloudinary.com/fullfraim/image/upload/v1621360001/ribhr70m6z94x7t1re94.gif" style="width:20rem;height:15rem;" />
        </div>
    }
</div>
@if (Model.Model.Count != 0)
{
    <div class="paging">
        <partial name="~/Views/Shared/Partials/_PagingPartial.cshtml" model="paginationModel" />
    </div>
}

<script>
    $(".page-link").on('click', function (event) {
        url = $(this).attr('href')
        paginationPhase(event, url);
    })
</script>

src/FullFraim/FullFraim.Web/Views/Shared/Partials/_ContestSubmissionPartial.cshtml
@model ContestSubmissionViewModel

<link href="~/css/hover-monochrome.css" rel="stylesheet" />

@if (Model.IsCurrentUserSubmission)
{
    <div class="card" style="margin-inline:1rem; margin-bottom:1rem; opacity:0.3">
        <div class="hovereffect">
            <img class="img-responsive" src="@Model.Image_Url" alt="Card image cap" style="width: 300px; height:250px">
            <div class="overlay">
                <h2>@Model.AuthorName</h2>
                <a class="info" asp-action="GiveReview" asp-controller="Dashboard">See submission</a>
            </div>
        </div>
    </div>
}
else
{
    <div class="card" style="margin-inline:1rem; margin-bottom:1rem;">
        <div class="hovereffect">
            <img class="img-responsive" src="@Model.Image_Url" alt="Card image cap" style="width: 300px; height:250px">
            <div class="overlay">
                <h2>@Model.AuthorName</h2>
                @if (Model.ActivePhase.Name == "PhaseII")
                {
                    <a asp-action="GiveReview" asp-controller="Dashboard" asp-route-contestId="@Model.ContestId"
                       asp-route-submitterId="@Model.AuthorId" class="info">Review</a>
                }
                else if (Model.ActivePhase.Name == "Finished")
                {
                    <a asp-action="DetailsReview" asp-controller="Dashboard" asp-route-contestId="@Model.ContestId"
                       asp-route-photoId="@Model.PhotoId" class="info">Details</a>
                }
            </div>
        </div>
    </div>
}

src/FullFraim/FullFraim.Web/Views/Shared/Partials/_ContestUserSubmissionPartial.cshtml
@model UserSubmissionViewModel

<link href="~/css/hover-monochrome.css" rel="stylesheet" />

<div class="card" style="margin-inline:1rem">
    <div class="hovereffect">
        <img class="img-responsive" src="@Model.PhotoUrl" alt="Card image cap" style="width: 300px; height:200px">
        <div class="overlay">
            <h2>@Model.SubmitterName</h2>
        </div>
    </div>
</div>

src/FullFraim/FullFraim.Web/Views/Shared/Partials/_EnrollPartial.cshtml
@model EnrollViewModel

<div class="contact-form-area">
    <div class="container-fluid">
        <form asp-action="Enroll" asp-controller="Dashboard" method="post" enctype="multipart/form-data" onsubmit="return EditAjaxPost(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="ContestId" value="@Model.ContestId" hidden />
            <div class="row">
                <div class="col-12 col-md-4">
                    <input asp-for="ImageTitle" type="text" class="form-control" placeholder="@Html.NameFor(x => x.ImageTitle)">
                    <span asp-validation-for="ImageTitle" class="text-danger"></span>
                </div>
                <div class="col-12 col-md-4">
                    <input asp-for="Photo" class="form-control" id="imgInp" placeholder="Subject">
                    <span asp-validation-for="Photo" class="text-danger"></span>
                <img id="blah" src="https://res.cloudinary.com/fullfraim/image/upload/v1622574796/ndetnuuzutpjpruvknjm.png" />
                </div>
                <div class="col-12 col-md-4">
                    <textarea asp-for="ImageDescription" class="form-control" placeholder="@Html.NameFor(x => x.ImageDescription)">
                    </textarea>
                    <span asp-validation-for="ImageDescription" class="text-danger"></span>
                </div>
                <div class="col-12 text-center">
                    <button type="submit" class="btn studio-btn mt-3">
                        <img src="~/img/core-img/logo-icon.png" alt=""> Enroll
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<script asp-append-version="true">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#imgInp").change(function () {
        readURL(this);
    });

    $(document).ready(function () {
        EditAjaxPost = form => {
            $.ajax({
                type: 'POST',
                url: form.action,
                data: new FormData(form),
                contentType: false,
                processData: false,
                success: function (res) {
                    if (res.isValid) {
                        location.reload();
                    }
                    else {
                        $(".modal-body").html('');
                        $(".modal-body").html(res);
                    }
                },
                error: function (err) {
                    location.reload();
                    alert("An error occured.");
                }
            })
            //to prevent default form submit event
            return false;
        };
    });
</script>

src/FullFraim/FullFraim.Web/Views/Shared/Partials/_FooterPartial.cshtml
<footer class="footer-area">
    <div class="container-fluid h-100">
        <div class="row h-100">
            <div class="col-12 h-100">
                <div class="footer-content h-100 d-md-flex align-items-center justify-content-between">
                    <div class="single-footer-content">
                        <img src="/img/core-img/map.png" alt="">
                        <a href="#">Blvd Libertad, 34 m05200 Arévalo</a>
                    </div>
                    <div class="single-footer-content">
                        <img src="/img/core-img/smartphone.png" alt="">
                        <a href="#">0034 37483 2445 322</a>
                    </div>
                    <div class="single-footer-content">
                        <img src="/img/core-img/envelope-2.png" alt="">
                        <a href="#">hello@company.com</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

src/FullFraim/FullFraim.Web/Views/Shared/Partials/_HeaderPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager

<style>
    .outlineText {
        color: #28bdaa !important;
        font-size: 1rem !important;
        font-weight: bold;
    }
</style>

<header class="header-area">
    <div class="container-fluid h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12 h-100">
                <div class="main-menu h-100">
                    <nav class="navbar h-100 navbar-expand-lg">
                        <a class="navbar-brand" asp-action="Index" asp-controller="Home">
                            <div>
                                <svg xmlns="http://www.w3.org/2000/svg" width="4rem" height="4rem" fill="currentColor" class="bi bi-camera2" viewBox="0 0 16 16" style="color: white; margin-bottom: -1vh;">
                                    <path d="M5 8c0-1.657 2.343-3 4-3V4a4 4 0 0 0-4 4z" />
                                    <path d="M12.318 3h2.015C15.253 3 16 3.746 16 4.667v6.666c0 .92-.746 1.667-1.667 1.667h-2.015A5.97 5.97 0 0 1 9 14a5.972 5.972 0 0 1-3.318-1H1.667C.747 13 0 12.254 0 11.333V4.667C0 3.747.746 3 1.667 3H2a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1h.682A5.97 5.97 0 0 1 9 2c1.227 0 2.367.368 3.318 1zM2 4.5a.5.5 0 1 0-1 0 .5.5 0 0 0 1 0zM14 8A5 5 0 1 0 4 8a5 5 0 0 0 10 0z" />
                                </svg>
                                <div style="color: white;">
                                    fullfr<span style=" color: #28bdaa; font-weight: bold;">aim</span>
                                </div>
                            </div>
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#studioMenu" aria-controls="studioMenu" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i> Menu</button>

                        <div class="collapse navbar-collapse" id="studioMenu">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item active">
                                    <a class="nav-link outlineText" asp-action="Index" asp-controller="Home">Home <span class="sr-only">(current)</span></a>
                                </li>
                                @if (SignInManager.IsSignedIn(User))
                                {

                                    <li class="nav-item">
                                        <a class="nav-link outlineText" asp-controller="Dashboard" asp-action="Index">dashboard</a>
                                    </li>

                                }
                                @if (User.IsInRole(Constants.Roles.Organizer))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link outlineText" asp-controller="User" asp-action="Index">Users</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link outlineText" asp-controller="Contest" asp-action="Create">Create Contest</a>
                                    </li>
                                }
                                <partial name="~/Views/Shared/Partials/_LoginPartial.cshtml">
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>

src/FullFraim/FullFraim.Web/Views/Shared/Partials/_PagingPartial.cshtml
@model PaginationPartialModel

@{
    string pageNumber = "1";
    if (Model.PageNumber != 0)
    {
        pageNumber = Model.PageNumber.ToString();
    }
    else
    {
        pageNumber = Context.Request.Query["PageNumber"].ToString();
    }

    int currentPage = String.IsNullOrEmpty(pageNumber) ? 1 : int.Parse(pageNumber);
}

<div>
    <nav aria-label="Page navigation example">
        <ul class="pagination" style="justify-content: center;">
            @if (currentPage > 2)
            {
                <li class="page-item">
                    <a class="page-link @Model?.Phase" asp-action="@Model.Action" asp-controller="@Model.Controller" asp-route-PageNumber="1" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                        <span class="sr-only"></span>
                    </a>
                </li>
            }
            @if (currentPage == 1)
            {
                <li class="page-item disabled">
                    <a class="page-link @Model?.Phase" asp-action="@Model.Action" asp-controller="@Model.Controller" asp-route-PageNumber="@(currentPage - 1)" aria-label="First">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link @Model?.Phase" asp-action="@Model.Action" asp-controller="@Model.Controller" asp-route-PageNumber="@(currentPage - 1)" aria-label="First">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
            }
            @if (currentPage > 2)
            {
                <li class="page-item disabled">
                    <a class="page-link">
                        ...
                    </a>
                </li>
            }
            @for (int i = currentPage; i < currentPage + 3; i++)
            {
                if ((i - 1 != 0) ^ (i - 1 > Model.TotalPages))
                {
                    if (i - 1 == currentPage)
                    {
                        <li class="page-item disabled">
                            <a class="page-link @Model?.Phase" asp-action="@Model.Action" asp-controller="@Model.Controller" asp-route-PageNumber="@(i - 1)">
                                @(i - 1)
                            </a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link @Model?.Phase" asp-action="@Model.Action" asp-controller="@Model.Controller" asp-route-PageNumber="@(i - 1)">
                                @(i - 1)
                            </a>
                        </li>
                    }
                }
            }
            @if (currentPage + 1 < Model.TotalPages)
            {
                <li class="page-item disabled">
                    <a class="page-link">
                        ...
                    </a>
                </li>
            }
            @if (currentPage == Model.TotalPages)
            {
                <li class="page-item disabled">
                    <a class="page-link @Model?.Phase" asp-action="@Model.Action" asp-controller="@Model.Controller" asp-route-PageNumber="@(currentPage + 1)" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link @Model?.Phase" asp-action="@Model.Action" asp-controller="@Model.Controller" asp-route-PageNumber="@(currentPage + 1)" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            }
            @if (currentPage + 1 < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link @Model?.Phase" asp-action="@Model.Action" asp-controller="@Model.Controller" asp-route-PageNumber="@Model.TotalPages" aria-label="Next">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            }
        </ul>
    </nav>
</div>